name: 'Deploy HelmFile'
description: 'Deploy on Kubernetes with HelmFile'
author: hello@cloudposse.com
branding:
  icon: 'file-text'
  color: 'white'
inputs:
  cluster:
    description: Cluster name
    required: true
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  helmfile-path:
    description: The path where lives the helmfile.
    required: false
    default: deploy
  helmfile:
    description: Helmfile name
    required: false
    default: helmfile.yaml
  operation:
    description: Operation with helmfiles. (valid options - `deploy`, `destroy`)
    required: true
    default: deploy
  environment:
    description: Helmfile environment
    required: false
    default: preview
  gitref-sha:
    description: Git SHA
    required: false
    default: ''
  namespace:
    description: Kubernetes namespace
    required: true
  image:
    description: Docker image
    required: true
  image-tag:
    description: Docker image tag
    required: true
  debug:
    description: Debug mode
    default: 'false'
    required: false
outputs:
  webapp-url:
    description: "Web Application url"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_REGION: ${{ inputs.aws-region }}
    ENVIRONMENT: ${{ inputs.environment }}
    HELMFILE: ${{ inputs.helmfile }}
    HELMFILE_PATH: ${{ inputs.helmfile-path }}
    NAMESPACE: ${{ inputs.namespace }}
    IMAGE_NAME: ${{ inputs.image }}
    IMAGE_TAG: ${{ inputs.image-tag }}
    OPERATION: ${{ inputs.operation }}
    GITREF_SHA: ${{ inputs.gitref-sha }}
    CLUSTER_NAME: ${{ inputs.cluster }}
    HELM_DEBUG: ${{ inputs.debug }}
